export const LANG_KEYWORDS = [
  'break',
  'defer',
  'import',
  'struct',
  'case',
  'else',
  'interface',
  'switch',
  'const',
  'for',
  'map',
  'type',
  'continue',
  'func',
  'range',
  'default',
  'global',
  'if',
  'return',
  'make',
]

export const LANG_KEYWORDS_ZH = [
  '跳出',
  '押后',
  '引入',
  '结构',
  '有辙',
  '或者',
  '否则',
  '接口',
  '找辙',
  '常量',
  '循环',
  '字典',
  '类型',
  '继续',
  '函数',
  '迭代',
  '没辙',
  '全局',
  '如果',
  '或者',
  '返回',
]

export const LANG_TYPES = [
  'bool',
  'string',
  'error',
  'map',
  'int',
  'int8',
  'int16',
  'int32',
  'int64',
  'i8',
  'i16',
  'i32',
  'i64',
  'rune',
  'uint',
  'uint8',
  'uint16',
  'uint32',
  'uint64',
  'u8',
  'u16',
  'u32',
  'u64',
  'uintptr',
  'byte',
  'float32',
  'float64',
  'f32',
  'f64',
  'complex64',
  'complex128',
  'c64',
  'c128',
]

export const LANG_TYPES_ZH = [
  '布尔',
  '字串',
  '错误',
  '整型',
  '微整型',
  '短整型',
  '普整型',
  '长整型',
  '微正整',
  '短正整',
  '普正整',
  '长正整',
  '符文',
  '字节',
  '单精',
  '双精',
  '单复',
  '双复',
]

export const LANG_BOOL = ['true', 'false']

export const LANG_BOOL_ZH = ['真', '假']

export const LANG_SNIPPETS = [
  {
    label: 'im',
    insertText: 'import "${1:pkg}"',
    detail: 'Snippet for import statement',
  },
  {
    label: 'ims',
    insertText: 'import (\n\t${1:pkg}\n)',
    detail: 'Snippet for a import block',
  },
  {
    label: 'co',
    insertText: 'const ${1:name} = ${2:value}',
    detail: 'Snippet for a constant',
  },
  {
    label: 'cos',
    insertText: 'const (\n\t${1:name} = ${2:value}\n)',
    detail: 'Snippet for a constant block',
  },
  {
    label: 'tyf',
    insertText: 'type ${1:name} func($3) $4',
    detail: 'Snippet for a type function declaration',
  },
  {
    label: 'tyi',
    insertText: 'type ${1:name} interface {\n\t$0\n}',
    detail: 'Snippet for a type interface',
  },
  {
    label: 'tys',
    insertText: 'type ${1:name} struct {\n\t$0\n}',
    detail: 'Snippet for a struct declaration',
  },
  {
    label: 'if',
    insertText: 'if ${1:cond} {\n\t$0\n}',
    detail: 'Snippet for if statement',
  },
  {
    label: 'ife',
    insertText: 'if ${1:cond} {\n\t$0\n} else {\n\t$0\n}',
    detail: 'Snippet for if else statement',
  },
  {
    label: 'iferr',
    insertText: 'if ${1:cond} != nil {\n\t$0\n}',
    detail: 'Snippet for if != nil statement',
  },
  {
    label: 'for',
    insertText: 'for ${1:i} := ${2:0}; $1 < ${3:count}; $1${4:++} {\n\t$0\n}',
    detail: 'Snippet for for statement',
  },
  {
    label: 'forr',
    insertText: 'for ${1:_, }${2:v} := range ${3:v} {\n\t$0\n}',
    detail: 'Snippet for for range statement',
  },
  {
    label: 'sw',
    insertText: 'switch ${1:expr} {\n\t$0\n}',
    detail: 'Snippet for switch statement',
  },
  {
    label: 'swc',
    insertText: 'switch ${1:expr} {\ncase ${2:cond}:\n\t$0\n}',
    detail: 'Snippet for switch case statement',
  },
  {
    label: 'swd',
    insertText: 'switch ${1:expr} {\ndefault:\n\t$0\n}',
    detail: 'Snippet for switch default statement',
  },
  {
    label: 'swcd',
    insertText: 'switch ${1:expr} {\ncase ${2:cond1}:\n\t$3\ndefault ${4:cond2}:\n\t$0\n}',
    detail: 'Snippet for switch default statement',
  },
  {
    label: 'df',
    insertText: 'defer ${1:func}()',
    detail: 'Snippet for defer statement',
  },
  {
    label: 'rt',
    insertText: 'return ${1:value}',
    detail: 'Snippet for return statement',
  },
  {
    label: 'br',
    insertText: 'break',
    detail: 'Snippet for break statement',
  },
  {
    label: 'cn',
    insertText: 'continue',
    detail: 'Snippet for continue statement',
  },
  {
    label: 'f',
    insertText: 'func ${1:name}($2) $3 {\n\t$0\n}',
    detail: 'Snippet for function declaration',
  },
]

export const LANG_SNIPPETS_ZH = [
  {
    label: '引',
    insertText: '引入 "${1:包}"',
    detail: '引入语句片段',
  },
  {
    label: '引入',
    insertText: '引入 (\n\t${1:包}\n)',
    detail: '引入块片段',
  },
  {
    label: '常',
    insertText: '常量 ${1:名称} = ${2:值}',
    detail: '常量片段',
  },
  {
    label: '常量',
    insertText: '常量 (\n\t${1:名称} = ${2:值}\n)',
    detail: '常量块片段',
  },
  {
    label: '类函',
    insertText: '类型 ${1:名称} 函数($3) $4',
    detail: '类型函数声明片段',
  },
  {
    label: '类接',
    insertText: '类型 ${1:名称} 接口 {\n\t$0\n}',
    detail: '类型接口片段',
  },
  {
    label: '类结',
    insertText: '类型 ${1:名称} 结构 {\n\t$0\n}',
    detail: '结构声明片段',
  },
  {
    label: '如',
    insertText: '如果 ${1:条件} {\n\t$0\n}',
    detail: '如果语句片段',
  },
  {
    label: '如否',
    insertText: '如果 ${1:条件} {\n\t$0\n} 否则 {\n\t$0\n}',
    detail: '如果否则语句片段',
  },
  {
    label: '循',
    insertText: '循环 ${1:i} := ${2:0}; $1 < ${3:计数}; $1${4:++} {\n\t$0\n}',
    detail: '循环语句片段',
  },
  {
    label: '循迭',
    insertText: '循环 ${1:_, }${2:值} := 迭代 ${3:集合} {\n\t$0\n}',
    detail: '循环迭代语句片段',
  },
  {
    label: '找',
    insertText: '找辙 ${1:表达式} {\n\t$0\n}',
    detail: '找辙语句片段',
  },
  {
    label: '找有',
    insertText: '找辙 ${1:表达式} {\n有辙 ${2:条件}:\n\t$0\n}',
    detail: '找辙有辙语句片段',
  },
  {
    label: '找没',
    insertText: '找辙 ${1:表达式} {\n没辙:\n\t$0\n}',
    detail: '找辙没辙语句片段',
  },
  {
    label: '押',
    insertText: '押后 ${1:函数}()',
    detail: '押后语句片段',
  },
  {
    label: '返',
    insertText: '返回 ${1:值}',
    detail: '返回语句片段',
  },
  {
    label: '跳',
    insertText: '跳出',
    detail: '跳出语句片段',
  },
  {
    label: '继',
    insertText: '继续',
    detail: '继续语句片段',
  },
  {
    label: '函',
    insertText: '函数 ${1:名称}($2) $3 {\n\t$0\n}',
    detail: '函数声明片段',
  },
]
